// Code generated by protoc-gen-go. DO NOT EDIT.
// source: moment-service-v1.proto

package community

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Media_Type int32

const (
	Media_JPG   Media_Type = 0
	Media_PNG   Media_Type = 1
	Media_VIDEO Media_Type = 2
	Media_GIF   Media_Type = 3
)

var Media_Type_name = map[int32]string{
	0: "JPG",
	1: "PNG",
	2: "VIDEO",
	3: "GIF",
}

var Media_Type_value = map[string]int32{
	"JPG":   0,
	"PNG":   1,
	"VIDEO": 2,
	"GIF":   3,
}

func (x Media_Type) String() string {
	return proto.EnumName(Media_Type_name, int32(x))
}

func (Media_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5975adeca29b6588, []int{1, 0}
}

// Define general Moment type
type CreateMomentRequest struct {
	// Type of = 1;
	PostBy               string   `protobuf:"bytes,1,opt,name=post_by,json=postBy,proto3" json:"post_by,omitempty"`
	ShortText            string   `protobuf:"bytes,2,opt,name=short_text,json=shortText,proto3" json:"short_text,omitempty"`
	Media                []*Media `protobuf:"bytes,3,rep,name=media,proto3" json:"media,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMomentRequest) Reset()         { *m = CreateMomentRequest{} }
func (m *CreateMomentRequest) String() string { return proto.CompactTextString(m) }
func (*CreateMomentRequest) ProtoMessage()    {}
func (*CreateMomentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5975adeca29b6588, []int{0}
}

func (m *CreateMomentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMomentRequest.Unmarshal(m, b)
}
func (m *CreateMomentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMomentRequest.Marshal(b, m, deterministic)
}
func (m *CreateMomentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMomentRequest.Merge(m, src)
}
func (m *CreateMomentRequest) XXX_Size() int {
	return xxx_messageInfo_CreateMomentRequest.Size(m)
}
func (m *CreateMomentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMomentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMomentRequest proto.InternalMessageInfo

func (m *CreateMomentRequest) GetPostBy() string {
	if m != nil {
		return m.PostBy
	}
	return ""
}

func (m *CreateMomentRequest) GetShortText() string {
	if m != nil {
		return m.ShortText
	}
	return ""
}

func (m *CreateMomentRequest) GetMedia() []*Media {
	if m != nil {
		return m.Media
	}
	return nil
}

// Image or video
type Media struct {
	TypeOf               Media_Type `protobuf:"varint,1,opt,name=typeOf,proto3,enum=ycode.comunity.moment.api.v1.Media_Type" json:"typeOf,omitempty"`
	Location             string     `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Media) Reset()         { *m = Media{} }
func (m *Media) String() string { return proto.CompactTextString(m) }
func (*Media) ProtoMessage()    {}
func (*Media) Descriptor() ([]byte, []int) {
	return fileDescriptor_5975adeca29b6588, []int{1}
}

func (m *Media) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Media.Unmarshal(m, b)
}
func (m *Media) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Media.Marshal(b, m, deterministic)
}
func (m *Media) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Media.Merge(m, src)
}
func (m *Media) XXX_Size() int {
	return xxx_messageInfo_Media.Size(m)
}
func (m *Media) XXX_DiscardUnknown() {
	xxx_messageInfo_Media.DiscardUnknown(m)
}

var xxx_messageInfo_Media proto.InternalMessageInfo

func (m *Media) GetTypeOf() Media_Type {
	if m != nil {
		return m.TypeOf
	}
	return Media_JPG
}

func (m *Media) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

type CreateMomentResponse struct {
	ResourceName         string   `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMomentResponse) Reset()         { *m = CreateMomentResponse{} }
func (m *CreateMomentResponse) String() string { return proto.CompactTextString(m) }
func (*CreateMomentResponse) ProtoMessage()    {}
func (*CreateMomentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5975adeca29b6588, []int{2}
}

func (m *CreateMomentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMomentResponse.Unmarshal(m, b)
}
func (m *CreateMomentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMomentResponse.Marshal(b, m, deterministic)
}
func (m *CreateMomentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMomentResponse.Merge(m, src)
}
func (m *CreateMomentResponse) XXX_Size() int {
	return xxx_messageInfo_CreateMomentResponse.Size(m)
}
func (m *CreateMomentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMomentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMomentResponse proto.InternalMessageInfo

func (m *CreateMomentResponse) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func init() {
	proto.RegisterEnum("ycode.comunity.moment.api.v1.Media_Type", Media_Type_name, Media_Type_value)
	proto.RegisterType((*CreateMomentRequest)(nil), "ycode.comunity.moment.api.v1.CreateMomentRequest")
	proto.RegisterType((*Media)(nil), "ycode.comunity.moment.api.v1.Media")
	proto.RegisterType((*CreateMomentResponse)(nil), "ycode.comunity.moment.api.v1.CreateMomentResponse")
}

func init() { proto.RegisterFile("moment-service-v1.proto", fileDescriptor_5975adeca29b6588) }

var fileDescriptor_5975adeca29b6588 = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xdf, 0x4b, 0xc2, 0x50,
	0x14, 0x6e, 0x2e, 0x35, 0x4f, 0x16, 0xe3, 0x16, 0x28, 0x52, 0x20, 0xf3, 0xc5, 0x28, 0xaf, 0x6c,
	0x3d, 0x85, 0x2f, 0xa1, 0x95, 0x18, 0xf8, 0x83, 0x25, 0x3d, 0xf4, 0x22, 0x73, 0x9e, 0x68, 0xd0,
	0xdd, 0x5d, 0xbb, 0x77, 0xc3, 0xfd, 0x07, 0xf5, 0xdc, 0x3f, 0x1c, 0xdb, 0x54, 0x0a, 0x42, 0xea,
	0xed, 0x7c, 0xdf, 0xbe, 0xef, 0x9c, 0x6f, 0xe7, 0x5c, 0xa8, 0x30, 0xce, 0xd0, 0x93, 0x2d, 0x81,
	0x41, 0xe4, 0x3a, 0xd8, 0x8a, 0x0c, 0xea, 0x07, 0x5c, 0x72, 0x72, 0x12, 0x3b, 0x7c, 0x81, 0xd4,
	0xe1, 0x2c, 0xf4, 0x5c, 0x19, 0xd3, 0x4c, 0x47, 0x6d, 0xdf, 0xa5, 0x91, 0xa1, 0xbf, 0x2b, 0x70,
	0xd4, 0x0b, 0xd0, 0x96, 0x38, 0x4c, 0x79, 0x0b, 0xdf, 0x42, 0x14, 0x92, 0x54, 0xa0, 0xe8, 0x73,
	0x21, 0x67, 0xf3, 0xb8, 0xaa, 0xd4, 0x95, 0x66, 0xc9, 0x2a, 0x24, 0xb0, 0x1b, 0x93, 0x53, 0x00,
	0xf1, 0xc2, 0x03, 0x39, 0x93, 0xb8, 0x94, 0xd5, 0x5c, 0xfa, 0xad, 0x94, 0x32, 0x53, 0x5c, 0x4a,
	0x72, 0x05, 0x79, 0x86, 0x0b, 0xd7, 0xae, 0xaa, 0x75, 0xb5, 0xb9, 0x6f, 0x36, 0xe8, 0xb6, 0xe9,
	0x74, 0x98, 0x48, 0xad, 0xcc, 0xa1, 0x7f, 0x2a, 0x90, 0x4f, 0x09, 0x72, 0x0d, 0x05, 0x19, 0xfb,
	0x38, 0x7e, 0x4e, 0x67, 0x1f, 0x9a, 0xcd, 0x3f, 0x74, 0xa1, 0xd3, 0xd8, 0x47, 0x6b, 0xe5, 0x23,
	0x35, 0xd8, 0x7b, 0xe5, 0x8e, 0x2d, 0x5d, 0xee, 0xad, 0x32, 0x6e, 0xb0, 0x7e, 0x01, 0xbb, 0x89,
	0x96, 0x14, 0x41, 0xbd, 0x9f, 0xf4, 0xb5, 0x9d, 0xa4, 0x98, 0x8c, 0xfa, 0x9a, 0x42, 0x4a, 0x90,
	0x7f, 0x1c, 0xdc, 0xdc, 0x8e, 0xb5, 0x5c, 0xc2, 0xf5, 0x07, 0x77, 0x9a, 0xaa, 0x77, 0xe0, 0xf8,
	0xe7, 0x7e, 0x84, 0xcf, 0x3d, 0x81, 0xa4, 0x01, 0x07, 0x01, 0x0a, 0x1e, 0x06, 0x0e, 0xce, 0x3c,
	0x9b, 0xe1, 0x6a, 0x4d, 0xe5, 0x35, 0x39, 0xb2, 0x19, 0x9a, 0x1f, 0x0a, 0x68, 0x3d, 0xce, 0xb2,
	0xd4, 0x0f, 0xd9, 0x65, 0x48, 0x08, 0xe5, 0xef, 0x1d, 0x89, 0xb1, 0xfd, 0xef, 0x7e, 0xb9, 0x4e,
	0xcd, 0xfc, 0x8f, 0x25, 0x0b, 0xdc, 0x3d, 0x7f, 0x3a, 0xcb, 0x4c, 0x0c, 0xdb, 0x69, 0x61, 0xfb,
	0xae, 0x68, 0x3b, 0xeb, 0x74, 0xed, 0xc8, 0xe8, 0x6c, 0xc0, 0xbc, 0x90, 0xbe, 0x9d, 0xcb, 0xaf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xa8, 0xbf, 0xeb, 0x03, 0x56, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CommunityServiceClient is the client API for CommunityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommunityServiceClient interface {
	CreateMoment(ctx context.Context, in *CreateMomentRequest, opts ...grpc.CallOption) (*CreateMomentResponse, error)
}

type communityServiceClient struct {
	cc *grpc.ClientConn
}

func NewCommunityServiceClient(cc *grpc.ClientConn) CommunityServiceClient {
	return &communityServiceClient{cc}
}

func (c *communityServiceClient) CreateMoment(ctx context.Context, in *CreateMomentRequest, opts ...grpc.CallOption) (*CreateMomentResponse, error) {
	out := new(CreateMomentResponse)
	err := c.cc.Invoke(ctx, "/ycode.comunity.moment.api.v1.CommunityService/CreateMoment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommunityServiceServer is the server API for CommunityService service.
type CommunityServiceServer interface {
	CreateMoment(context.Context, *CreateMomentRequest) (*CreateMomentResponse, error)
}

// UnimplementedCommunityServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCommunityServiceServer struct {
}

func (*UnimplementedCommunityServiceServer) CreateMoment(ctx context.Context, req *CreateMomentRequest) (*CreateMomentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMoment not implemented")
}

func RegisterCommunityServiceServer(s *grpc.Server, srv CommunityServiceServer) {
	s.RegisterService(&_CommunityService_serviceDesc, srv)
}

func _CommunityService_CreateMoment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMomentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).CreateMoment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ycode.comunity.moment.api.v1.CommunityService/CreateMoment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).CreateMoment(ctx, req.(*CreateMomentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CommunityService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ycode.comunity.moment.api.v1.CommunityService",
	HandlerType: (*CommunityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMoment",
			Handler:    _CommunityService_CreateMoment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "moment-service-v1.proto",
}
